# For running integration tests.
version: "3.0"
services:
  multi-site-dashboard-go:
    image: msd
    container_name: msd
    build:
      dockerfile: Dockerfile
    depends_on:
      - timescaledb
      - kafka
      - nginx
    environment:
      - GO_ENV=PRODUCTION
    ports:
      - 8000:8000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  timescaledb:
    container_name: timescaledb1
    image: timescale/timescaledb-ha:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  kafka:
    container_name: kafka1
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092
    # https://github.com/apache/kafka/blob/trunk/docker/examples/README.md
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  nginx:
    container_name: nginx
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
