// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/golang-migrate/migrate/v4"
	"github.com/jackc/pgx/v5/pgxpool"
	"go.uber.org/zap"
	"multi-site-dashboard-go/config"
	"multi-site-dashboard-go/repository"
)

import (
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func WireLogger() (*zap.Logger, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger, err := config.ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	return logger, nil
}

func WirePgConnPool(ctx context.Context) (*pgxpool.Pool, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	pool, err := repository.ProvidePgConnPool(ctx, configConfig)
	if err != nil {
		return nil, err
	}
	return pool, nil
}

func WirePgMigrateInstance(relativePath string) (*migrate.Migrate, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	driver, err := repository.ProvidePgDriver(configConfig)
	if err != nil {
		return nil, err
	}
	migrateMigrate, err := repository.ProvidePgMigrateInstance(driver, relativePath)
	if err != nil {
		return nil, err
	}
	return migrateMigrate, nil
}
