// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MachineResourceUsage struct {
	ID        int32            `json:"id"`
	Machine   string           `json:"machine"`
	Metric1   int32            `json:"metric1"`
	Metric2   int32            `json:"metric2"`
	Metric3   int32            `json:"metric3"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}
