// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MachineResourceUsage struct {
	ID        int32            `db:"id" json:"id"`
	Machine   string           `db:"machine" json:"machine" validate:"required"`
	Metric1   int32            `db:"metric1" json:"metric1" validate:"required"`
	Metric2   int32            `db:"metric2" json:"metric2" validate:"required"`
	Metric3   int32            `db:"metric3" json:"metric3" validate:"required"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"createdAt"`
}
