// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"
)

type Querier interface {
	CreateMachineResourceUsage(ctx context.Context, arg CreateMachineResourceUsageParams) (MachineResourceUsage, error)
	GetAggregatedMachineResourceUsage(ctx context.Context, arg GetAggregatedMachineResourceUsageParams) ([]GetAggregatedMachineResourceUsageRow, error)
	UpdateMachineResourceUsage(ctx context.Context, arg UpdateMachineResourceUsageParams) error
}

var _ Querier = (*Queries)(nil)
