// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"
)

type Querier interface {
	ExecWithPgTx(ctx context.Context, cb func(Querier) (interface{}, error)) func() (interface{}, error)
	CreateMachineResourceUsage(ctx context.Context, arg CreateMachineResourceUsageParams) (MachineResourceUsage, error)
	GetMachineResourceUsage(ctx context.Context, machine string) ([]MachineResourceUsage, error)
	UpdateMachineResourceUsage(ctx context.Context, arg UpdateMachineResourceUsageParams) error
}

var _ Querier = (*Queries)(nil)
