// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package resourcetracking

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MachineResourceUsage struct {
	ID        int32
	Machine   string
	Metric1   int32
	Metric2   int32
	Metric3   int32
	CreatedAt pgtype.Timestamp
}
